services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgre_taskmanager'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - .env
